#!/usr/bin/env bash
# Install nginx on web-01 server

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
