#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
touch /var/www/html/404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '24 i \\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
