#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get upgrade -y
sudo apt install -y haproxy
sudo sed -i "$ aENABLED=1" /etc/init.d/haproxy
echo "
frontend load_balancer
    bind *:80
    mode http
    default_backend webserver
backend webserver
    balance roundrobin
    server 3643-web-01 35.196.111.72:80 check
    server 3643-web-02 3.80.62.168:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
