#!/usr/bin/env bash
# Debugging my Ubuntu container's Nginx installation
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
